// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJygd8ti3mISUf40bAYhBPANSoMcgq0P4',
    appId: '1:836803540175:android:82e87e54a509687d2d73ba',
    messagingSenderId: '836803540175',
    projectId: 'lyon-1bad1',
    storageBucket: 'lyon-1bad1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0HUHuNOVi5PyyNSN_WMGlUrI04zPmdbE',
    appId: '1:836803540175:ios:5f845de258e5cd042d73ba',
    messagingSenderId: '836803540175',
    projectId: 'lyon-1bad1',
    storageBucket: 'lyon-1bad1.appspot.com',
    androidClientId: '836803540175-1l4pdcei8afquc5o2oaltvpqvg7kr401.apps.googleusercontent.com',
    iosClientId: '836803540175-9cvsq74cu6gk9i68lq7570mrn7lg421v.apps.googleusercontent.com',
    iosBundleId: 'com.lyonjo.company',
  );
}
