// ignore: file_names
const Map<String, String> enUS = {
  /////////////////////////////////////
  "next": "Next",
  "back": "Back",
  "rental": "Rent a Car",
  "transportation": "Transportation",
  "car available": "Available Car",
  "start_date": "Start Date",
  "please_enter_start_date": "Please Enter Start Date",
  "start_time": "Start Time",
  "please_enter_start_time": "Please Enter Start Time",
  "end_date": "End Date",
  "please_enter_end_date": "Please Enter End Date",
  "end_time": "End Time",
  "please_enter_end_time": "Please Enter End Time",
  "per_day_month": "per day/month",
  "add_trip": "Add Trip",
  "search": "Search",
  "about_us": "About Us",
  "notification": "Notification",
  "setting": "Setting",
  "cart": "Cart",
  "contact_us": "Contact Us",
  "our location": "Our Location",
  "help_center": "Help Center",
  "logout": "Logout",
  "date": "Date",
  "name": "Name",
  "service": "Service",
  "status": "Status",
  "are u sure delete20jd":
      "Are you sure you want to delete this order? Because you want to cancel after 24 hours of making the order, a fine of 20 JOD will be added.",
  "are u sure delete": "Are you sure you want to delete Order?",
  "cancel": "Cancel",
  "details": "Details",
  "delete": "Delete",
  "offer": "Offer",
  "airport": "Airport Street",
  "bayader": "Al-Bayader",
  "open map": "Open Map",
  "airport office": "Airport Office",
  "everyday": "Everyday",
  "24 hours": "24 Hours",
  "amman office": "Amman Office",
  "sunday - thursday": "Sunday - Thursday",
  "9am - 6pm": "9AM - 6PM",
  "per_day": "per day",
  "book": "Book",
  "internal_specifications": "ّInternal Specifications:",
  "features": "Features:",
  "safety_features": "Safety Features:",
  "show_less": "Show Less",
  "show_more": "Show More",
  "determine_start_and_end_location": "Determine start and end location",
  "start_location": "Start Location",
  "please_enter_this_field_start_location":
      "Please enter this field start location",
  "end_location": "End Location",
  "please_enter_this_field_end_location":
      "Please Enter this field end location",
  "message": "Message",
  "ok": "OK",
  "amman": "Amman",
  "king_hussien_bridge": "King Hussien Bridge",
  "queen_alia_airport": "Queen Alia Airport",
  "confirm": "Confirmation",
  "type": "Type",
  "return_date": "Return Date",
  "return_time": "Return Time",
  "pick_up_location": "Pick up location",
  "drop_off_location": "Drop Off location",
  "number_of_days": "Number of days",
  "number_of_vehicle": "Number of Vehicle",
  "select_extra_item": "Select Extra Item",
  "summary": "Summary",
  "car_price_day": "Car Price / Day : ",
  "jd": " JD ",
  "total_car_price": "Total Car Price : ",
  "extra_items": "Extra Items : ",
  "tax": "Tax : 16%",
  "total": "Total : ",
  "filling_of_gasoline": "Filling of Gasoline",
  "car_seat": "Car Seat",
  "non_smoking_car": "Non Smoking Car",
  "ashtray": "Ashtray",
  "insurance": "Insurance",
  "none": "None",
  "continue": "Continue",
  "checkout": "Check Out",
  "where_are_you_located": "Where are you located?",
  "inside_jordan": "Inside Jordan",
  "outside_of_jordan": "Outside Of Jordan",
  "please_choose_your_location": "Please choose your location",
  "upload_license_photos": "Upload license photo",
  "upload_passport_id_photos": "Upload Passport Photo",
  "upload_ticket_photo": "Upload Flight Ticket",
  "please_upload_images": "Please upload images",
  "terms_and_conditions": "Terms and Conditions",
  "term1": "The lessee’s age must be 27 or above.",
  "term2":
      "The lessee must have an ongoing driving license for at least 2 years. Cars will not be rented out for people who have a driving license for less than 2 years.",
  "term3":
      "Payments are not refundable, so we kindly require customers to confirm their rental periods.",
  // "term4":"In case of booking a car and cancelling within 24 hours, there will be no fees.",
  "term5":
      "Cars receiving and delivery locations in the following places: Queen Alia International Airport - King Hussein Bridge - Amman.",
  "term5_1_1": "Airport office location/off-airport",
  "term5_1_2":
      "When you arrive at Queen Alia International Airport, there will be a person carrying a paper with your name written on it, who will hand you the car and complete the contract procedures at the airport and not at the office.",
  "term5_1_3":
      "When you return to deliver the car, you go to the office outside the airport and hand the vehicle over to the employee. The employee delivers you to the airport.",
  "term5_2":
      "We do not have an office on the King Hussein Bridge. In the event of a reservation, the car will be unloaded with a driver, the car will be delivered to you at the bridge, and the driver will return with you to the Amman office.",
  "term5_2_1":
      "When the car is delivered, you will go to the Amman office and be delivered to the bridge without any additional fees.",
  "term6":
      "After booking a car at the airport, there will be a person in the arrival hall waiting for you, holding a paper with your name written on it. They will hand your booked car over, and then you have to take videos of it from the inside and the outside.",
  "term7":
      "The lessee will return the vehicle in the same condition as it was when they got it handed over , based on the videos, if newer hits or scratches are found, there will be a fine put on the lessee based on the market’s prices and the cost of repairs.",
  "term8":
      "When booking a car inside of Amman, you will be contacted for the purpose delivering your booked car to your location. This service is not available outside of Amman, noting that it’s available in on specific areas in Amman.",
  "term9_1": "Extra fines will apply if below conditions are met:",
  "term9_2": "Unclean on the outside: 5 JD.",
  "term9_3": "Unclean on the outside & inside: 10 JD.",
  "term9_4": "Unclean seats: 25 JD.",
  "term9_5":
      "Our customers are kindly requested to keep the cars clean, because they represent our core values at Lyon.",
  "term10":
      "Traffic violations are calculated from the date and time of receiving the car to the date and time of returning the car. So please make sure you close the contract at the time you return the car.",
  "term11":
      "In case of booking using the mobile application or website, please note that the booking status is not confirmed until an Email is received containing the booking number, which is also located in the Reservation screen.",
  "term12_1": "Regarding traffic accidents:",
  "term12_2":
      "If the lessee is the cause of the accident, a 390 JD fine will be applied. (Croquet issuing fees for the insurance company).",
  "term12_2_1":
      "In the case of purchasing insurance, the accident clauses are considered void.",
  "term12_3":
      "If the lessee isn’t the cause of the accident, no fines will be applied and you can get another car if any are available in the same price.",
  "term12_4": "In case of stealing the car, a 2000 JD fine will be applied.",
  "term12_5": "In case of totaling the car, a 3000 JD fine will be applied.",
  "term12_5_2":
      "When purchasing vehicle insurance Includes scratches and accidents It does not include complete damage, fire or theft.",
  "term12_5_3":
      "Traffic accident notices are brought in all cases, The company's number is contacted in all cases.",
  "term12_5_4":
      "In case of cash payment, an insurance amount of 200 dinars will be paid.",
  "term12_5_5":
      "In the case of payment by visa, the security deposit is not paid.",
  "term12_6":
      "You can find your due bills through the application or website and you can create an account statement for a whole year.",
  "term14_1":
      "Important note: Kindly use the application to book for yourself, and not for anyone else. Because the provided information is your information.",
  "term14_2":
      "In case of booking a car for someone else using your information, Lyon has the right to cancel it.",
  "term15":
      "Booking through our application gives you gifts and points which you can use later to get money back or discounts.",
  "term15_1":
      "Car delivery in Amman until six o'clock in the evening (the office is closed).",
  "term15_2": "Car delivery at the airport 24 hours.",
  "term16_1": "Dear customer, you can contact us through:",
  "term16_2": "The WhatsApp icon on the bottom right of the screen.",
  "term16_3": "Our Email: Support@lyon-jo.com",
  "term17": "Daily allowed distance is 200 km / 24 hours",
  "term18":
      "The company has the right to cancel the reservation if the reservation amount is unreasonable, even if the reservation is approved, and the amount paid will be returned via Visa.",
  "term19": "Additional amounts after booking :",
  "term19_1": "The Visa commission is calculated at 2.5%.",
  "term19_2": "Airport parking fees are borne by the renter.",
  "i_read_and_agree": "I read and agree",
  "language": "Language",
  "login": "LogIn",
  "enter_your_phone_number": "Enter Your Phone Number",
  "please_enter_phone_number": "Please Enter Phone Number",
  "phone_number_not_valid": "Phone Number Not Valid",
  "please_enter_password": "Please Enter Password",
  "password": "Password",
  "forget_password": "Forget Password?",
  "signup": "Register",
  "choose_image": "Take a photo",
  "choose_image_gallery": "Choose Image from Gallery",
  "please_enter_first_name": "Enter First Name",
  "first_name": "First Name",
  "please_enter_last_name": "Enter Last Name",
  "last_name": "Last Name",
  "please_enter_correct_email": "Please Enter Correct Email",
  "email": "Email",
  "please_enter_email": "Please Enter Email",
  "password_must_be_over_8_characters": "Password must be over 8 characters",
  "confirm_password": "Confirm Password",
  "please_enter_confirm_password": "Please Enter Confirm Password",
  "birthdate": "Birthdate",
  "please_enter_birthdate": "Please Enter Birthdate",
  "determine_location": "Determine Location",
  "please_enter_location": "Please Enter Location",
  "please_choose_currency": "Please choose a Currency",
  "personal_identification": "Personal Identification",
  "front_image": "Front Image",
  "back_image": "Back Image",
  "please_upload_licnes_image": "Please upload license image",
  "save_image": "Save Image",
  "pictures_have_been_saved": "Pictures have been saved",
  "delete_photo": "Delete photo",
  "add_image": "Add Image",
  "please_upload_image": "Please Upload Image",
  "chairman_message": "CHAIRMAN MESSAGE",
  "chairman_message1":
      "Lyon Group was set up more than 5 years ago, and since then has maintained its services in the field of car rental, transportation, inbound, and outbound as its core business, serving many people from all over the world. Keeping our vision, “value for money & client satisfaction” as a compass. Lyon is one of the few companies that can offer all services in tours and car rental with flexible and efficient solutions, as a one stop supplier.  Whereas at the same time they enable them to compete effectively in their own source markets. We invite you to share our vision and benefit from our expertise, professionalism, flexibility, personalized approach, strong purchasing power and comprehensive product portfolio. In the following pages, we hope that we will give you an overview of our organization, history, services and key persons and you will give us the opportunity to examine together the areas where we could work on a fruitful and mutually beneficial basis in the future. Rafat Abualhaj Chairman & C.E.O.",
  "who_we_are": "WHO WE ARE?",
  "who_we_are1":
      "LYON Group is company founded in 2015 as part of Abu Al Haj Group of Investments. With more than 5 years of experience in hospitality industry, we expanded our business to provide our valuable clients with all services related to tourism such as Car Rental, Transportation, Airline Ticket Reservation, Hotel Accommodation, Visa support and exciting range of tour packages and excursions for FIT’s & Groups. Our expertise and proficiency are united in harmony to match desires and travel needs of our valuable clients and partners. We aim provide you with an excellent and comprehensive travel services most efficiently at a reasonable cost and connect it to the technology era effectively.",
  "who_we_are2": "Our Companies:",
  "who_we_are3": "Lyon for car rental",
  "who_we_are4": "Lyon for travel",
  "who_we_are5": "Marvell for car rental",
  "mission": "MISSION",
  "mission1":
      "To be your preferred auto leasing and travel partner.Provide customers with tailored leasing solutions that meet each customer’s unique automotive requirements in Jordan while offering the most comprehensive range of vehicles and leasing packages starting from low cost to ultimate luxury, provide Our experience in travel , provide best rates for air tickets , hotels ,  provide a logistical framework that contributes to a customer’s business development, expansion and strategic achievement.",
  "accreditation": "ACCREDITATION",
  "accreditation1":
      "Lyon Travel & Tours is accredited by MOTA (Jordan Ministry of Tourism& Antiquities), JSTA (Jordan Society of Travel & Tourism Agent) and JTB (Jordan Tourism Board)",
  "services": "SERVICES",
  "services1":
      "Lyon is into Car rental/Leasing company that delivers dedicated automotive leasing and fleet management services to individual and institutional customers in Jordan. We provide world class transport solutions and services that are tailored to each company’s transport, leasing and fleet requirements. Let us take care of your transport needs so that you can focus on your business and grow.Lyon operates in a very competitive market, and like you, we are very ambitious. We aim to become a World Class company.We will only achieve this goal by being a customer-focused, sales-driven business. This means we listen to what our customers have to say and then act upon it.Lyon maintains a management team with over 10 years of international leasing experience in corporate and luxury leasing services, who deliver exceptional knowledge and customer service expertise across the entire organization.From the first customer touch point to the highly trained and uniformed chauffeurs, our intensive staff training programs ensure customers get the best and most efficient service, obsessed with the desire to exceed our elite customers’ expectations.Our Services Lyon is committed to unparalleled quality encompassing all market demands for both business and leisure.We can provide long-term leasing programs while maintaining incomparable car rental privileges.We offer a fleet of vehicles carefully built up to cater all requirements, supported by a dedicated team of car maintenance specialists with a sole objective: “Customer Satisfaction”.Our modern fleet services offering the finest top of the line models of vehicles with extensive choices such as saloons, sports, luxury cars, SUVs, minivans.Available on daily monthly or yearly basis at the best market rates, they are meticulously maintained and regularly serviced by authorized representatives and always in pristine condition to ensure paramount safety on the road.",
  "services2": "Our Mission:",
  "services3":
      "To be your preferred auto leasing and fleet transport partner.Provide customers with tailored leasing solutions that meet each customer’s unique automotive requirements in Jordan while offering the most comprehensive range of vehicles and leasing packages from low cost to ultimate luxury.To provide a logistical framework that contributes to a customer’s business development, expansion and strategic achievement.",
  "services4": "Why Us? What Sets Us Apart from Our Competitors?",
  "services5": "We are fiercely customer service oriented.",
  "services6": "We are focused 100% on our customers’ needs.",
  "services7":
      "We are flexible and can tailor custom lease packages depending on what our customers want.",
  "services8":
      "Dynamic team and well-trained personnel to provide personalized services to customer.",
  "services9":
      "We have the youngest fleet of well-maintained and regularly serviced cars for an unconstrained pure driving pleasure in complete safety.",
  "services10":
      "Our comprehensive full coverage insurance policies are second to none. Dedicated 24/7 Emergency Assistance and Breakdown Service with rapid response team to handle any situation our customer comes across.",
  "services11": "Vast,international experience in fleet management.",
  "services12":
      "Excellent track records for managing and providing transport solutions and services.",
  "services13":
      "Most competitive rates for long and short term lease available Jordan.",
  "services14":
      "Products &amp; Services offered by Lyon Rent A Car We offer a well-diversified range of services including:",
  "services15": "Self and Chauffeur driven Long Term Car rental services.",
  "services16": "Full service Lease operation.",
  "services17": "Fleet management contracts.",
  "services18": "Long term rentals and lease operation programs.",
  "services19": "Tailor-made car rental, leasing programs and fleet solutions.",
  "services20": "Long Term Shuttle services and exclusive tours.",
  "services21": "Fleet outsourcing, consultancy and management services.",
  "services22":
      "Insurance Lyon provides a complete comprehensive insurance solution through the largest Insurance Companies in Jordan. The vehicles are fully covered with insurance including collision damage waiver CDW insurance.",
  "services23": "Our Fleet:",
  "services24":
      "Lyon offers a comprehensive palette of comfortable, powerful, and fully featured brand new vehicles. Put us to test: We will provide you with a stunning range of the latest models that are synonymous with reliability, safety, quality and outstanding technology.One look at our range of exciting and head turning cars is all it takes to discover our difference.",
  "services25": "Where do we go from here…?",
  "services26":
      "We have expansion plans to build more representation offices in different countries. Stay tuned for our future development:",
  "services27":
      "Our expertise in planning will keeps us ahead of our competitors.",
  "services28":
      "Jordan Road works with the best in the business of ground handling and has access to the most modern, fully equipped fleet of cars to buses, from limousines to 4x4s, we offer our guests exactly what they need to feel comfortable and satisfied as they journey through this beautiful country.",
  "services29": "Visa",
  "services30":
      "Lyon provides the simplest solution for processing your travel visa. Say goodbye to endless research and dealing with foreign governments. We enable travelers to process visas from a computer, smartphone, or tablet. Travel agents, destination management companies and corporations can use lyon-jo.com to process any travel visa. We provide the best solution in the market.",
  "services31": "Limousine & VIP services",
  "services32":
      "our goal is to provide professional and affordable transportation services across the local Winnipeg area. Our motto is 100% customer satisfaction, our professional and courteous staff is at your service 27/7. Our luxury executive Town cars,We are equipped with latest amenities to provide your with safe and comfortable travel. Our professionally managed, trustworthy service allows you to spend more time on what’s important to you. Just leave the rest to us. We know Winnipeg inside and out insuring you can sit back, relax, and rely on us to get you where you need to go in comfort and style.",
  "services33": "Tours",
  "services34": "Why Lyon Tours?",
  "services35":
      "With unrivalled knowledge and expertise in the tourism sector, we are committed to bringing you the finest travel experiences available where the possibilities are endless.We pride ourselves in being destination and travel experts equipped to tailor your trips as per your individual needs, budgets and travel requirements.We will take you out of the guidebooks and into a world you’re waiting to discover. Our multilingual, friendly and passionate staff will help you choose what best fits your needs whether in person at our conveniently located offices in Amman, or via phone, Skype or email.",
  "services36": "Outbound:",
  "services37":
      "Lyon travel has created this section to make sure that you always get the best out of your travel needs at the best prices possible. Check here periodically to see the hot deals we have created for you",
  "services38": "Ticketing:",
  "services39":
      "Purchasing tickets at any airline of your choice has never been easier! Just choose any destination and contact us to help you book your flight",
  "services40": "Visa Services:",
  "services41":
      "Lyon tours Provides a wide range of services to visa applicants, all aimed at enhancing customer experience in public services with an automated and seamless process. However, Lyon tour does not play any part in the decision-making process behind visa applications being granted or denied.",
  "services42": "Inbound:",
  "services43": "Lyon Tours",
  "services44":
      "Organizes trips primarily to Jordan. Next to that we can also organize overland trips to Jordan’s neighboring countries in the Middle-East. We have extended knowledge of the region. Two of our partners were born and raised in the ancient tribes of Petra.We know our way around Jordan from our own experience for years on end.As a result Lyon Tours Can compose almost every program possible; meeting the customers’ individual groups needs and wishes.Traveling to Jordan with Lyon tours Will give travelers an opportunity to see the real colorful Jordan.We take pride in making every trip we organize a unique experience for our clients.We stand for offering a travel experience beyond belief.Our Target Customer satisfaction quality services is the prime target of Lyon tours As we always provided the best quality in terms of service to its customers.The travelers have always had a satisfied note of the services provided by us.",
  "services45":
      "Now you can have a comfortable Holiday in Jordan where in you leave all the worries to us.Right from the arrival at the airport to personalized assistance of departure, we take care of all the needs of the travelers. Our guests just sit back enjoy their holidays with all the value for the money they have spent.",
  "services46": "Travel insurance",
  "services47": "Lyon is a leader in providing quality travel insurance.",
  "services48": "we are one of the most experienced in the industry.",
  "services49":
      "Travel protection keeps you safe and supported on your travels.",
  "services50":
      "Protect your dream vacation and your future and get a quote today. Dream. Explore. Travel On.",
  "services51": "Flights",
  "services52":
      "Search thousands of cheap tickets and cheap flight offers to your favorite destinations around the world. Book vacations.",
  "services53": "Hotels",
  "services54":
      "You can book any hotel in the world by us with the best prices.",
/////////////////////  Transportion ///////////////////////
  "car": "Car",
  "1_4_people": "1 ~ 4 People",
  "capacity_3_luggage": "Capacity: 3 Luggage",
  "van": "Van",
  "5_7_people": "5 ~ 7 People",
  "capacity_10_luggage": "Capacity: 10 Luggage",
  "please_choose_vehicle":
      "Please choose the vehicle based on the number of passengers or luggage.",
  "select_destination": "Select Destination",
  "please_enter_destination": "Please Enter Destination",
  "pickup_date": "Pickup Date",
  "please_enter_date": "Please Enter Date",
  "please_enter_time": "Please Enter Time",
  "ticket_uploaded_successfully": "Ticket Uploaded Successfully",
  "passport_uploaded_successfully": "Passport Uploaded Successfully",
  "license_uploaded_successfully": "License Uploaded Successfully",
  "please_upload_ticket": "Please Upload Ticket",
  "please_upload_passport": "Please Upload Passport",
  "submit": "Submit",
  "send_verify_code": "Send Verify Code",
  "payment": "Payment",
  "payment_method": "Payment Method",
  "cash_on_delivery": "Cash On Delivery",
  "credit_card": "Credit Card",
  "total_price": "Total Price : ",
  "complete": "Complete",
  "error": "Error",
  "you_are_blacklisted": "You are blacklisted!",
  "warning": "Warning",
  "please_pay_the_amounts_due": "Please pay the amounts due",
  "order_details": "Order Details",
  "car_name": "Car Name",
  "phone": "Phone",
  "total_price_2": "Total Price",
  "destination": "Destination",
  "additional_notes": "Additional Notes",
  "vehicle_type": "Vehicle Type",
  "no_offers_available": "No offers available",
  "view_image": "View Image",
  "edit_profile": "Edit Profile",
  "address": "Address",
  "street": "Street",
  "update_passport_image": "Update Passport Image",
  "update_license_image": "Update License Image",
  "save": "Save",
  "phone_number_(optional)": "Phone Number (requierd)",
  "email_(optional)": "Email (You can't change it)",
  "address_(optional)": "Address (optional)",
  "street_(optional)": "Street (optional)",
  "trip": "Trip",
  "tourism_program": "Tourism Program",
  "you_must_add_at_least_two_trips": "you must add at least two trips",
  "program": "Program",
  "are_you_sure_to_exit": "Are you sure to exit ?",
  "select_country": "Select Country",
  "account_statment": "Account Statment",
  "account_statement_details": "Account Statement Details",
  "delete_account": "Delete Account",
  "are_you_sure_to_delete_your_account": "Are you sure to delete your account?",
  "no": "No",
  "yes": "Yes",
  "term1_trip":
      "Payments are non-refundable, so we ask customers to confirm their booking period.",
// "term2_trip":"Payments are non-refundable.",
// "term3_trip":"In case of reservation and cancellation after 24 hours, there will be an additional fee that will be charged in full.",
  "term4_trip":
      "After booking, at the airport there will be a person in the arrival hall waiting for you, carrying a paper with your name written on it, and will take you to the place of the flight.",
  "term5_trip":
      "When booking the flight inside Amman, you will be contacted for the purpose of inquiring about your residence address in Jordan.",
  "term6_trip":
      "Additional fines will be applied if the following conditions are met:",
  "term6_trip_1":
      "5 dinars are added to airport flights to the areas: Shafa Badran, Tabarbour and Abu Nseir.",
  "term6_trip_2":
      "An amount of 10 dinars will be added in the event that the vehicle is not kept clean from the inside during the trip.",
  "term7_trip":
      "Our customers are kindly requested to keep the cars clean, as they are our core values ​​at Lyon.",
  "term8_trip":
      "Please note that if you book flights, the price includes tax, car, driver and petrol.",
  "term9_trip": "Please do not smoke inside the vehicle.",
  "term10_trip":
      "In the case of a reservation using the mobile application or website, please note that the status of the reservation is not confirmed until an email containing the reservation number is also received on the reservation screen.",
  "term11_trip":
      "You can find your outstanding bills through the mobile application, and you can create an account statement for a year.",
  "term12_trip":
      "Important note: Please use the app to book for yourself and not for anyone else. Because the information provided is your information.",
  "term13_trip":
      "In the event that a vehicle is booked for someone else using your information, Leon has the right to cancel it.",
  "term14_trip":
      "Booking through our app gives you gifts and points that you can later use to redeem money or discounts.",
  "term15_trip": "Dear customer, you can contact us through:",
  "term15_trip_1": "WhatsApp icon at the bottom right of the screen.",
  "term15_trip_2": "Our email: support@lyon-jo.com",
  "later": "Later",
  "update_now": "Update Now",
  "update_desc":
      "There is a newer version of app available please update it now.",
  "new_update_available": "New Update Available",
  "you_do_not_have_an_account_statement":
      "You do not have An Account Statement",
  "change_language": "Change Language",
  "arabic": "Arabic",
  "english": "English",
////////////////////// Company ////////////////////////////////////////
////////////////////// Company ////////////////////////////////////////
////////////////////// Company ////////////////////////////////////////

  "my_orders": "My Orders",
  "invoice": "Invoice",
  "you_do_not_have_any_reservations": "You do not have any reservations",
  "email_has_been_sent_successfully": "Email has been sent successfully.",
  "enter_project_name": "Enter Project Name",
  "select_project_name": "Select project Name",
  "company_name": "Company Name",
  "project_name": "Project Name",
  "all_times": "All Times",
  "all_dates": "All Dates",
  "number_of_trips": "Num. Trips",
  "please_choose_vehicle_2": "please choose Vehicle",
  "select_vehicle": "Select Vehicle",
  "please_enter_project_name": "please enter project name",
  "please_enter_name": "please enter name",
  "please_choose_location": "please choose location",
  "select_location": "Select Location",
  "location": "Location",
  "a_network_error_has_occurred":
      "A network error has occurred, please try again.",
  "order_date": "Order Date",
  "price_day": "Price / Day",
  "please_check_time_and_date": "please check time and date",
  "phone_number": "Phone Number",
  "order_created_successfully": "Order created successfully.",
  "license_image": "License Image",
  "similar": "Similar",
  "Per_day_Month": "Per day / Month",
  "full_day_program": "Full Day Program",
  "company": "Company",
  "contract_number": "ID",
  "pickup_location": "Pickup Location",
  "dropoff_location": "Dropoff Location",
  "please_select_pickup_location": "Please select pickup location",
  "please_select_dropoff_location": "Please select dropoff location",
  "one_way": "One Way",
  "multi_way": "Multi Way",
  "full_program": "Full Program",
  "trip2": "Trip",
  "amount": "Amount",
  "you_must_upload_image": "You must upload image",
  "This_trip_is_not_avaliable": "This trip is not avaliable",
  "contact_us_for_more_details": "Contact us for more details",
  "rental_term_1":
      "When paying by Visa, no financial amount is pledged or a security deposit is required.",
  "rental_term_2":
      "When paying in cash, a security deposit of 200 dinars is required.",
  "rental_term_3":
      "You can pay in cash, and upon arrival at the airport, you can pay by Visa to avoid paying a security deposit.",
  "rental_term_4":
      "In case of cancellation, please cancel the reservation at least 48 hours in advance to avoid any financial charges.",
  "check_your_email": "Please Check Your Email",
  "payment_title": "Lyon Jo Payment",
  "note": "Press Submit to complete the payment",
  "please_wait": "Please Wait",
  "or_press_submit": "Or Press Submit",
  "biometrics_notsupported": "Biometrics not supported",
  "biometrics_activate": "Activate FingerPrint / FaceID",
  "number_check": "Is this your phone number?",
  "back_button": "Back",
  "confirm_button": "Confirm",
  "guest": "Login as a guest",
  "alert": "Alert",
  "please_login": "Please Login to Show Your Orders",
  "hotels": "Hotels",
  "appertment": "Appertment",
  "flight": "Flights",
  "cottages": "Cottages",
  "tents": "Bubbles Wadi Rum",
  "account_statement": "Account Statement",
  "send_it_by_email": "Send it by Email",
  "you_do_not_have_any_account_statement":
      "You do not have any Account Statement",
  "trip_keyword": "Trip",
  "we_are_calculation_your_trips_price": "We are calculation your trips price",
  "did_not_receive_code": "Did not receive code?",
  "resend_code": "Resend Code",
};
